version: "3.8"
services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=tesa
    volumes:
      - mongodb_data:/data/db  

  broker_mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app_network

  mqtt-publisher:
    build: 
      context: ./mqtt-publisher
      dockerfile: dockerfile
    container_name: mqtt_publisher
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - broker_mqtt

networks:
  app_network:
    driver: bridge


volumes:
  mongodb_data:    
  mosquitto_data: 
  mosquitto_log: